### ISSUE TITLE
Add option to configure api-end-points outside of task

### ISSUE THREAD

**Issue by lukas-bednar** [machacekondra/ovirt-engine-ansible#1]
``` yaml
tasks:
  - name: List datacenter
    data_centers:
      api_action: list
      api_url: https://ondra.local:8443/ovirt-engine/api
      api_username: admin@internal
      api_password: 1234567
      api_insecure: True
      param_list:
        search: "name=dcx"
    register: dc
```

Isn't it possible to define  API details in separate config file, and reference that connection by name?
For example:
role/vars/main.yml

``` yaml
my-ovirt:
  url: https://ondra.local:8443/ovirt-engine/api
  username: admin@internal
  password: 1234567
  insecure: True
```

role/tasks/main.yaml

``` yaml
- name: List datacenter
  data_centers:
    api: {{ my-ovirt | dict }}
    action: list
    param_list:
      search: "name=dcx"
  register: dc
```

**Comment by machacekondra** [comment]
Just noticed the issue, sorry.

Yes, I will change it, and most probably call it 'auth', and add support to SSO token.
btw the result syntax of tasks most probably will be:

``` yaml
---
- hosts: local,
  remote_user: root
  vars:
    auth:
      url: https://ondra.local:8443/ovirt-engine/api
      username: admin@internal
      password: 1234567
  tasks:
  - name: List dc
    data_centers:
      auth: {{ auth }}
      method: list
      parameters:
        search: "name=dcx"
    register: dc

  - name: Add datacenter
    data_centers:
      auth: {{ auth }}
      method: add
      parameters:
        data_center:
          name: dcx
          local: True

  - name: List vm disk
    vm_disks:
      auth: {{ auth }}
      method: list
      parameters:
        search: "name=diskx"
    register: vm_disk

  - name: assign perm
    assignedpermissions:
      auth: {{ auth }}
      method: add
      href: "{{ vm_disk.href }}"
      parameters:
        permission:
          role: x
          user: y
```

Feel free to comment.
